version: '3'

services:
  poller:
    image: poller_python_image
    build:
      context: .
      dockerfile: ./deploy/python.dockerfile
    volumes:
      - "./src:/var/www"
    ports:
      - "8080:8000"