version: '3'

services:
  poller:
    image: poller_python_image
    build:
      context: .
      dockerfile: ./deploy/python.dockerfile
    command: "python /var/www/manage.py runserver 0.0.0.0:8000"
    ports:
      - "80:8000"